pipeline {
    agent any 
    environment {
        PATH = "/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin"
    }
    stages {
        stage('Clone Repository') { 
            steps {
                sh ' rm -rf ./*'
                sh 'git clone https://github.com/codygreen/Automation_Webinar.git'
            }
        }
        stage('Build Web App') { 
            dir("Automation_Webinar/code/3*") {
                sh 'export TF_VAR_name=${params.APP_NAME}'
                /*sh 'terraform get --update'
                sh 'terraform init' 
                sh 'terraform apply --auto-approve'*/
            }
        }
        stage('Configure Web App') {
            echo params.APP_NAME
            echo parama.GIT_REPO_URL
            /*dir("Automation_Webinar/code/3*") {
                sh 'ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook -i ./inventory ./demo-app.yaml'
            }*/
        }
    }
}